// State to cities mapping for a few countries
const stateCities = {
  // India
  AndhraPradesh: [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Tirupati",
    "Kakinada",
    "Kadapa",
    "Anantapur",
  ],
  ArunachalPradesh: [
    "Itanagar",
    "Naharlagun",
    "Tawang",
    "Pasighat",
    "Roing",
    "Ziro",
    "Bomdila",
    "Aalo",
    "Tezu",
    "Changlang",
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Karimganj",
    "Sivasagar",
    "Goalpara",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Mahasamund",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Sanquelim",
    "Valpoi",
    "Quepem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Nadiad",
  ],
  Haryana: [
    "Faridabad",
    "Gurugram",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
  ],
  HimachalPradesh: [
    "Shimla",
    "Mandi",
    "Solan",
    "Dharamshala",
    "Una",
    "Nahan",
    "Bilaspur",
    "Hamirpur",
    "Chamba",
    "Kullu",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Chas",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangalore",
    "Hubli",
    "Belagavi",
    "Davanagere",
    "Ballari",
    "Tumakuru",
    "Shivamogga",
    "Bidar",
    "Hospet",
    "Raichur",
    "Hassan",
    "Udupi",
    "Kolar",
    "Chikkamagaluru",
    "Vijayapura",
    "Bagalkot",
    "Mandya",
    "Chitradurga",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kollam",
    "Thrissur",
    "Alappuzha",
    "Palakkad",
    "Malappuram",
    "Kottayam",
    "Kannur",
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Morena",
    "Shivpuri",
    "Guna",
    "Chhindwara",
    "Betul",
    "Harda",
    "Hoshangabad",
    "Khajuraho",
    "Mandla",
    "Neemuch",
    "Panna",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Damoh",
    
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Navi Mumbai",
    "Kolhapur",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Jalgaon",
    "Parbhani",
    "Panvel",
    "Sangli",
    "Satara",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Churachandpur",
    "Kakching",
    "Ukhrul",
    "Senapati",
    "Chandel",
    "Tamenglong",
    "Jiribam",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Baghmara",
    "Williamnagar",
    "Resubelpara",
    "Mairang",
    "Nongstoin",
    "Khliehriat",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Lawngtlai",
    "Mamit",
    "Saitual",
    "Hnahthial",
  ],
  Nagaland: [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Mon",
    "Phek",
    "Kiphire",
    "Longleng",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Batala",
    "Pathankot",
    "Moga",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Pali",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Gyalshing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Singtam",
    "Soreng",
    "Chungthang",
    "Ravangla",
  ],
  TamilNadu: [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukudi",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Ramagundam",
    "Khammam",
    "Mahbubnagar",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Ambassa",
    "Belonia",
    "Khowai",
    "Sonamura",
    "Teliamura",
    "Bishalgarh",
  ],
  UttarPradesh: [
    "Lucknow",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Nainital",
    "Pithoragarh",
    "Almora",
  ],
  WestBengal: [
    "Kolkata",
    "Asansol",
    "Siliguri",
    "Durgapur",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
  ],
  // Union Territories
  AndamanNicobar: [
    "Port Blair",
    "Garacharma",
    "Bamboo Flat",
    "Prothrapur",
    "Rangat",
    "Mayabunder",
    "Diglipur",
    "Hut Bay",
    "Neil Island",
    "Havelock Island",
  ],
  Chandigarh: ["Chandigarh"],
  DadraNagarHaveliDamanDiu: ["Silvassa", "Daman", "Diu"],
  Delhi: [
    "New Delhi",
    "Dwarka",
    "Rohini",
    "Saket",
    "Karol Bagh",
    "Janakpuri",
    "Laxmi Nagar",
    "Vasant Kunj",
    "Pitampura",
    "Mayur Vihar",
    "Connaught Place",
    "Rajouri Garden",
    "Shahdara",
    "Narela",
    "Najafgarh",
    "Palam",
    "Okhla",
    "Chanakyapuri",
    "Greater Kailash",
    "Vikaspuri",
  ],
  JammuKashmir: [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Udhampur",
    "Kathua",
    "Sopore",
    "Rajouri",
    "Poonch",
    "Pulwama",
  ],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Minicoy",
    "Bitra",
    "Chetlat",
    "Kiltan",
  ],
  Puducherry: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  // USA
  California: ["Los Angeles", "San Francisco", "San Diego", "Sacramento"],
  Texas: ["Houston", "Dallas", "Austin", "San Antonio"],
  "New York": ["New York City", "Buffalo", "Rochester", "Albany"],
  // Canada
  Ontario: ["Toronto", "Ottawa", "Mississauga", "Brampton"],
  Quebec: ["Montreal", "Quebec City", "Laval", "Gatineau"],
  "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby"],
  // Australia
  "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Albury"],
  Victoria: ["Melbourne", "Geelong", "Ballarat", "Bendigo"],
  Queensland: ["Brisbane", "Gold Coast", "Cairns", "Townsville"],
};

export default stateCities;
